# BRUNO MARCOS SANTOS

projeto: main.o estatistica.o 
	gcc -o projeto main.o estatistica.o -lm
main.o: main.c estatistica.h
	gcc -c main.c
estatistica.o: estatistica.c estatistica.h 
	gcc -c estatistica.c